version: '3.8'

services:
  app:
    image: acervofacil-app:1.0.0
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/acervofacilbd
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    networks:
      - rede_local

  db:
    image: postgres:12.0-alpine
    tty: true
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=acervofacilbd
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - rede_local

  pgadmin:
    image: dpage/pgadmin4
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - "9000:80"
    depends_on:
      - db
    networks:
      - rede_local

volumes:
  pgdata:

networks:
  rede_local:
    driver: bridge